# Generated by Django 3.0.2 on 2020-01-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'MisssionStatement',
                'verbose_name_plural': 'MisssionStatement',
            },
        ),
    ]
