# Generated by Django 3.0.2 on 2020-01-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/')),
                ('header_school', models.TextField(default='')),
                ('about_school', models.TextField(default='')),
                ('first_para', models.TextField(default='')),
                ('second_para', models.TextField(default='')),
                ('testimony_name_one', models.CharField(default='', max_length=50)),
                ('testimony_details_one', models.TextField(default='')),
                ('testimony_name_two', models.CharField(default='', max_length=50)),
                ('testimony_details_two', models.TextField(default='')),
                ('testimony_name_three', models.CharField(default='', max_length=50)),
                ('testimony_details_three', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Headmistress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/headmistress/')),
                ('name', models.CharField(default='', max_length=50)),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Headmistress',
                'verbose_name_plural': 'Headmistress',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/message/')),
                ('name', models.CharField(default='', max_length=50)),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/principal/')),
                ('name', models.CharField(default='', max_length=50)),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Principal',
            },
        ),
        migrations.CreateModel(
            name='VicePrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/vice-principal/')),
                ('name', models.CharField(default='', max_length=50)),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Vice-Principal',
                'verbose_name_plural': 'Vice-Principal',
            },
        ),
    ]
