# Generated by Django 3.0.2 on 2020-01-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('post', models.CharField(default='', max_length=150)),
                ('student_name', models.CharField(default='', max_length=150)),
            ],
            options={
                'verbose_name': 'StudentCouncil',
                'verbose_name_plural': 'StudentCouncil',
            },
        ),
    ]
