# Generated by Django 3.0.2 on 2020-01-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_lower', models.TextField(default='')),
                ('admission_hs', models.TextField(default='')),
                ('fees_payment', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Admissions',
                'verbose_name_plural': 'Admissions',
            },
        ),
    ]
