# Generated by Django 3.0.2 on 2020-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForceBehind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='forcebehind/')),
                ('name', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('paragraph', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'ForceBehind',
                'verbose_name_plural': 'ForceBehind',
            },
        ),
    ]
