# Generated by Django 3.0.2 on 2020-01-16 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_year', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='', max_length=250)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('category_year',),
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('circular_notice', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('circular_details_two', models.TextField(default='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circular.Category')),
            ],
            options={
                'verbose_name': 'Circular',
                'verbose_name_plural': 'Circulars',
                'ordering': ('circular_notice',),
            },
        ),
    ]
